### ISSUE TITLE
docs: document release process

### ISSUE THREAD

**Issue by csabapalfi** [yaorg/node-measured#66]
Hi @fieldju,

Apologies about the issues around #64. I'm not sure if I understand the current release process and somehow Travis kept adding tags so I cancelled the last build.

Probably the root cause is that I manually created a tag? Is there any documentation about how the release process works?

**Comment by fieldju** [comment]
@csabapalfi I am traveling right now for Memorial Day weekend here in the states. I will investigate what happened sometime this weekend or possibly Tuesday after I get back home.

**Comment by csabapalfi** [comment]
Ah, ok. It’s a long weekend in the UK as well. 😊

**Comment by csabapalfi** [comment]
I believe we might have an issue with relying on `curl https://github.com/yaorg/node-measured/releases/latest` as that might return draft releases as well (i.e. as soon as you draft a release it creates the tag and triggers Travis). 

I think what confused the publish script was a draft release for v1.41.0 that still was returned as latest (even after my v1.42.0) hence the never ending release version mismatch and Travis being triggered repeatedly.

**Comment by csabapalfi** [comment]
Basically we just have to be mindful that even if a draft release is created on Github it'll trigger the Travis build since the tag is already created and that can lead to confusion one i.e. if the draft release is then published or any other release gets created in the meantime.

**Comment by fieldju** [comment]
I think we can come up with better logic that will prevent the infinite release bug. I approved the PR documenting the warning as well as the release process. I will take a look at the script / APIs available to see if there is some more rails we can stand up to prevent run away releases.
